### ISSUE TITLE
Rediriger le port de mailhoger vers une addresse

### ISSUE THREAD

**Issue by jcalise6891** [OFP-CDA-Mulhouse-2020/parisportif3#1]

**Comment by jcalise6891** [comment]
Résolu via le commit : "Correction route mailhog"

**Comment by Neila142** [comment]
Réglé par d672718d5eb5c03df65de82f01fa5a18cd2aef2e 

Le reste j'ai fais des bêtises car je sais pas bien utilisé les pull requests...
